apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: team-admin
  lifecycle: experimental